// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aiserver/v1/automations.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cursor/terraform-provider-cursor/internal/proto/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AutomationsServiceName is the fully-qualified name of the AutomationsService service.
	AutomationsServiceName = "aiserver.v1.AutomationsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AutomationsServiceCreateAutomationProcedure is the fully-qualified name of the
	// AutomationsService's CreateAutomation RPC.
	AutomationsServiceCreateAutomationProcedure = "/aiserver.v1.AutomationsService/CreateAutomation"
	// AutomationsServiceGetAutomationProcedure is the fully-qualified name of the AutomationsService's
	// GetAutomation RPC.
	AutomationsServiceGetAutomationProcedure = "/aiserver.v1.AutomationsService/GetAutomation"
	// AutomationsServiceUpdateAutomationProcedure is the fully-qualified name of the
	// AutomationsService's UpdateAutomation RPC.
	AutomationsServiceUpdateAutomationProcedure = "/aiserver.v1.AutomationsService/UpdateAutomation"
	// AutomationsServiceDeleteAutomationProcedure is the fully-qualified name of the
	// AutomationsService's DeleteAutomation RPC.
	AutomationsServiceDeleteAutomationProcedure = "/aiserver.v1.AutomationsService/DeleteAutomation"
)

// AutomationsServiceClient is a client for the aiserver.v1.AutomationsService service.
type AutomationsServiceClient interface {
	CreateAutomation(context.Context, *connect.Request[v1.CreateAutomationRequest]) (*connect.Response[v1.CreateAutomationResponse], error)
	GetAutomation(context.Context, *connect.Request[v1.GetAutomationRequest]) (*connect.Response[v1.GetAutomationResponse], error)
	UpdateAutomation(context.Context, *connect.Request[v1.UpdateAutomationRequest]) (*connect.Response[v1.UpdateAutomationResponse], error)
	DeleteAutomation(context.Context, *connect.Request[v1.DeleteAutomationRequest]) (*connect.Response[v1.DeleteAutomationResponse], error)
}

// NewAutomationsServiceClient constructs a client for the aiserver.v1.AutomationsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAutomationsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AutomationsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	automationsServiceMethods := v1.File_aiserver_v1_automations_proto.Services().ByName("AutomationsService").Methods()
	return &automationsServiceClient{
		createAutomation: connect.NewClient[v1.CreateAutomationRequest, v1.CreateAutomationResponse](
			httpClient,
			baseURL+AutomationsServiceCreateAutomationProcedure,
			connect.WithSchema(automationsServiceMethods.ByName("CreateAutomation")),
			connect.WithClientOptions(opts...),
		),
		getAutomation: connect.NewClient[v1.GetAutomationRequest, v1.GetAutomationResponse](
			httpClient,
			baseURL+AutomationsServiceGetAutomationProcedure,
			connect.WithSchema(automationsServiceMethods.ByName("GetAutomation")),
			connect.WithClientOptions(opts...),
		),
		updateAutomation: connect.NewClient[v1.UpdateAutomationRequest, v1.UpdateAutomationResponse](
			httpClient,
			baseURL+AutomationsServiceUpdateAutomationProcedure,
			connect.WithSchema(automationsServiceMethods.ByName("UpdateAutomation")),
			connect.WithClientOptions(opts...),
		),
		deleteAutomation: connect.NewClient[v1.DeleteAutomationRequest, v1.DeleteAutomationResponse](
			httpClient,
			baseURL+AutomationsServiceDeleteAutomationProcedure,
			connect.WithSchema(automationsServiceMethods.ByName("DeleteAutomation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// automationsServiceClient implements AutomationsServiceClient.
type automationsServiceClient struct {
	createAutomation *connect.Client[v1.CreateAutomationRequest, v1.CreateAutomationResponse]
	getAutomation    *connect.Client[v1.GetAutomationRequest, v1.GetAutomationResponse]
	updateAutomation *connect.Client[v1.UpdateAutomationRequest, v1.UpdateAutomationResponse]
	deleteAutomation *connect.Client[v1.DeleteAutomationRequest, v1.DeleteAutomationResponse]
}

// CreateAutomation calls aiserver.v1.AutomationsService.CreateAutomation.
func (c *automationsServiceClient) CreateAutomation(ctx context.Context, req *connect.Request[v1.CreateAutomationRequest]) (*connect.Response[v1.CreateAutomationResponse], error) {
	return c.createAutomation.CallUnary(ctx, req)
}

// GetAutomation calls aiserver.v1.AutomationsService.GetAutomation.
func (c *automationsServiceClient) GetAutomation(ctx context.Context, req *connect.Request[v1.GetAutomationRequest]) (*connect.Response[v1.GetAutomationResponse], error) {
	return c.getAutomation.CallUnary(ctx, req)
}

// UpdateAutomation calls aiserver.v1.AutomationsService.UpdateAutomation.
func (c *automationsServiceClient) UpdateAutomation(ctx context.Context, req *connect.Request[v1.UpdateAutomationRequest]) (*connect.Response[v1.UpdateAutomationResponse], error) {
	return c.updateAutomation.CallUnary(ctx, req)
}

// DeleteAutomation calls aiserver.v1.AutomationsService.DeleteAutomation.
func (c *automationsServiceClient) DeleteAutomation(ctx context.Context, req *connect.Request[v1.DeleteAutomationRequest]) (*connect.Response[v1.DeleteAutomationResponse], error) {
	return c.deleteAutomation.CallUnary(ctx, req)
}

// AutomationsServiceHandler is an implementation of the aiserver.v1.AutomationsService service.
type AutomationsServiceHandler interface {
	CreateAutomation(context.Context, *connect.Request[v1.CreateAutomationRequest]) (*connect.Response[v1.CreateAutomationResponse], error)
	GetAutomation(context.Context, *connect.Request[v1.GetAutomationRequest]) (*connect.Response[v1.GetAutomationResponse], error)
	UpdateAutomation(context.Context, *connect.Request[v1.UpdateAutomationRequest]) (*connect.Response[v1.UpdateAutomationResponse], error)
	DeleteAutomation(context.Context, *connect.Request[v1.DeleteAutomationRequest]) (*connect.Response[v1.DeleteAutomationResponse], error)
}

// NewAutomationsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAutomationsServiceHandler(svc AutomationsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	automationsServiceMethods := v1.File_aiserver_v1_automations_proto.Services().ByName("AutomationsService").Methods()
	automationsServiceCreateAutomationHandler := connect.NewUnaryHandler(
		AutomationsServiceCreateAutomationProcedure,
		svc.CreateAutomation,
		connect.WithSchema(automationsServiceMethods.ByName("CreateAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	automationsServiceGetAutomationHandler := connect.NewUnaryHandler(
		AutomationsServiceGetAutomationProcedure,
		svc.GetAutomation,
		connect.WithSchema(automationsServiceMethods.ByName("GetAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	automationsServiceUpdateAutomationHandler := connect.NewUnaryHandler(
		AutomationsServiceUpdateAutomationProcedure,
		svc.UpdateAutomation,
		connect.WithSchema(automationsServiceMethods.ByName("UpdateAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	automationsServiceDeleteAutomationHandler := connect.NewUnaryHandler(
		AutomationsServiceDeleteAutomationProcedure,
		svc.DeleteAutomation,
		connect.WithSchema(automationsServiceMethods.ByName("DeleteAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aiserver.v1.AutomationsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AutomationsServiceCreateAutomationProcedure:
			automationsServiceCreateAutomationHandler.ServeHTTP(w, r)
		case AutomationsServiceGetAutomationProcedure:
			automationsServiceGetAutomationHandler.ServeHTTP(w, r)
		case AutomationsServiceUpdateAutomationProcedure:
			automationsServiceUpdateAutomationHandler.ServeHTTP(w, r)
		case AutomationsServiceDeleteAutomationProcedure:
			automationsServiceDeleteAutomationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAutomationsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAutomationsServiceHandler struct{}

func (UnimplementedAutomationsServiceHandler) CreateAutomation(context.Context, *connect.Request[v1.CreateAutomationRequest]) (*connect.Response[v1.CreateAutomationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aiserver.v1.AutomationsService.CreateAutomation is not implemented"))
}

func (UnimplementedAutomationsServiceHandler) GetAutomation(context.Context, *connect.Request[v1.GetAutomationRequest]) (*connect.Response[v1.GetAutomationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aiserver.v1.AutomationsService.GetAutomation is not implemented"))
}

func (UnimplementedAutomationsServiceHandler) UpdateAutomation(context.Context, *connect.Request[v1.UpdateAutomationRequest]) (*connect.Response[v1.UpdateAutomationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aiserver.v1.AutomationsService.UpdateAutomation is not implemented"))
}

func (UnimplementedAutomationsServiceHandler) DeleteAutomation(context.Context, *connect.Request[v1.DeleteAutomationRequest]) (*connect.Response[v1.DeleteAutomationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aiserver.v1.AutomationsService.DeleteAutomation is not implemented"))
}
